import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageDir = join(scriptDir, "..");
const abisDir = join(packageDir, "abis");
const outFile = join(packageDir, "src", "index.ts");

function toExportName(fileName: string): string {
  const base = fileName.replace(/\.json$/, "");
  const camel = base.charAt(0).toLowerCase() + base.slice(1);
  return `${camel}Abi`;
}

function main(): void {
  const files = readdirSync(abisDir)
    .filter((name) => name.endsWith(".json"))
    .sort();

  if (files.length === 0) {
    throw new Error(`No ABI json files found in ${abisDir}`);
  }

  const lines: string[] = ["// Generated by scripts/generate.ts. Do not edit by hand.", ""];

  for (const file of files) {
    const contents = readFileSync(join(abisDir, file), "utf8");
    const abi: unknown = JSON.parse(contents);
    const exportName = toExportName(file);
    lines.push(`export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;`, "");
  }

  writeFileSync(outFile, lines.join("\n"));
  console.log(`Wrote ${files.length} ABI exports to ${outFile}`);
}

main();
