-- Generated by infra/postgres/gen-stub.ts from vendor/agora-next/prisma/schema.prisma.
-- Do not edit by hand: re-run the generator instead.

\connect agora_web3

CREATE SCHEMA IF NOT EXISTS "fleet";
CREATE SCHEMA IF NOT EXISTS "agora";
CREATE SCHEMA IF NOT EXISTS "config";
CREATE SCHEMA IF NOT EXISTS "snapshot";

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'dao_slug' AND n.nspname = 'config'
  ) THEN
    CREATE TYPE "config"."dao_slug" AS ENUM ('OP', 'ENS', 'UNI', 'NOUNS', 'LYRA', 'ETHERFI', 'UNISWAP', 'CYBER', 'SCROLL', 'DERIVE', 'PGUILD', 'BOOST', 'XAI', 'B3', 'DEMO', 'LINEA', 'TOWNS', 'SYNDICATE', 'ZEROG', 'DEMO2', 'DEMO4', 'DEMO3', 'SHAPE', 'FLEET');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'chain' AND n.nspname = 'config'
  ) THEN
    CREATE TYPE "config"."chain" AS ENUM ('optimism-mainnet', 'ethereum-mainnet');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'contract_type' AND n.nspname = 'config'
  ) THEN
    CREATE TYPE "config"."contract_type" AS ENUM ('governor', 'token', 'alligator', 'proposal_types_configurator');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'dao' AND n.nspname = 'config'
  ) THEN
    CREATE TYPE "config"."dao" AS ENUM ('optimism');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'env' AND n.nspname = 'config'
  ) THEN
    CREATE TYPE "config"."env" AS ENUM ('dev', 'prod');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'proposal_type' AND n.nspname = 'config'
  ) THEN
    CREATE TYPE "config"."proposal_type" AS ENUM ('STANDARD', 'APPROVAL', 'OPTIMISTIC', 'SNAPSHOT', 'OFFCHAIN');
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "fleet"."advanced_delegatees" (
  "pair" text,
  "from" text,
  "to" text,
  "delegated_amount" numeric,
  "delegated_share" numeric,
  "block_number" bigint,
  "contract" text,
  "transaction_hash" text
);

CREATE TABLE IF NOT EXISTS "fleet"."advanced_voting_power" (
  "delegate" text,
  "vp_allowance" numeric,
  "vp_delegatable_allowance" numeric,
  "delegated_vp" numeric,
  "advanced_vp" numeric,
  "subdelegated_share" numeric,
  "contract" text
);

CREATE TABLE IF NOT EXISTS "fleet"."authority_chains_snaps" (
  "id" text,
  "delegate" text,
  "rules" jsonb,
  "chain" text[],
  "proxy" text,
  "balance" numeric,
  "allowance" numeric,
  "contract" text,
  "balance_block_number" bigint,
  "balance_ordinal" numeric
);

CREATE TABLE IF NOT EXISTS "fleet"."delegate_changed_events" (
  "chain_id" integer,
  "address" text,
  "block_number" bigint,
  "block_hash" text,
  "log_index" integer,
  "transaction_index" integer,
  "transaction_hash" text,
  "delegator" text,
  "from_delegate" text,
  "to_delegate" text
);

CREATE TABLE IF NOT EXISTS "fleet"."delegatees" (
  "delegator" text,
  "delegatee" text,
  "block_number" bigint,
  "balance" numeric,
  "contract" text,
  "transaction_hash" text
);

CREATE TABLE IF NOT EXISTS "fleet"."delegates" (
  "delegate" text,
  "contract" text,
  "num_of_delegators" numeric,
  "direct_vp" numeric,
  "advanced_vp" numeric,
  "voting_power" numeric
);

CREATE TABLE IF NOT EXISTS "fleet"."proposal_types" (
  "id" text,
  "contract" text,
  "block_number" bigint,
  "proposal_type_id" text,
  "quorum" text,
  "approval_threshold" text,
  "name" text,
  "inputs" jsonb
);

CREATE TABLE IF NOT EXISTS "fleet"."proposals_v2" (
  "proposal_id" text,
  "contract" text,
  "proposer" text,
  "description" text,
  "ordinal" numeric,
  "created_block" bigint,
  "start_block" text,
  "end_block" text,
  "cancelled_block" bigint,
  "queued_block" bigint,
  "executed_block" bigint,
  "proposal_data" jsonb,
  "proposal_data_raw" text,
  "proposal_type" text,
  "proposal_type_data" jsonb,
  "proposal_results" jsonb,
  "created_transaction_hash" text,
  "cancelled_transaction_hash" text,
  "queued_transaction_hash" text,
  "executed_transaction_hash" text
);

CREATE TABLE IF NOT EXISTS "fleet"."staked_deposits" (
  "deposit_id" bigint,
  "depositor" text,
  "beneficiary" text,
  "delegatee" text,
  "amount" numeric
);

CREATE TABLE IF NOT EXISTS "fleet"."votable_supply_v2" (
  "votable_supply" text
);

CREATE TABLE IF NOT EXISTS "fleet"."voter_stats" (
  "voter" text,
  "proposals_voted" bigint,
  "participation_rate" double precision,
  "last_10_props" numeric,
  "for" bigint,
  "abstain" bigint,
  "against" bigint,
  "proposals_proposed" bigint,
  "contract" text
);

CREATE TABLE IF NOT EXISTS "fleet"."votes" (
  "transaction_hash" text,
  "proposal_id" text,
  "voter" text,
  "support" text,
  "weight" numeric,
  "reason" text,
  "block_number" bigint,
  "params" text,
  "start_block" text,
  "description" text,
  "proposal_data" jsonb,
  "proposal_type" text,
  "contract" text,
  "chain_id" integer
);

CREATE TABLE IF NOT EXISTS "fleet"."voting_power" (
  "delegate" text,
  "voting_power" text,
  "contract" text
);

CREATE TABLE IF NOT EXISTS "fleet"."voting_power_snaps" (
  "id" text,
  "delegate" text,
  "balance" text,
  "block_number" bigint,
  "ordinal" numeric,
  "transaction_index" integer,
  "log_index" integer,
  "contract" text
);

CREATE TABLE IF NOT EXISTS "fleet"."vote_cast_events" (
  "transaction_hash" text,
  "proposal_id" text,
  "voter" text,
  "support" text,
  "weight" numeric,
  "reason" text,
  "block_number" bigint,
  "params" text,
  "contract" text
);

CREATE TABLE IF NOT EXISTS "fleet"."vote_cast_with_params_events" (
  "transaction_hash" text,
  "proposal_id" text,
  "voter" text,
  "support" text,
  "weight" numeric,
  "reason" text,
  "block_number" bigint,
  "params" text,
  "contract" text
);

CREATE TABLE IF NOT EXISTS "agora"."delegate_statements" (
  "address" text,
  "dao_slug" "config"."dao_slug",
  "signature" text,
  "payload" jsonb,
  "twitter" text,
  "discord" text,
  "email" text,
  "created_at" timestamp,
  "updated_at" timestamp,
  "warpcast" text,
  "endorsed" boolean,
  "scw_address" text,
  "notification_preferences" jsonb,
  "stage" text,
  "message_hash" text,
  "created_at_ts" timestamp,
  "updated_at_ts" timestamp
);

CREATE TABLE IF NOT EXISTS "agora"."address_metadata" (
  "address" text,
  "kind" text,
  "dao_slug" "config"."dao_slug",
  "metadata" jsonb,
  "created_at" timestamp
);

CREATE TABLE IF NOT EXISTS "agora"."safe_tracked_transactions" (
  "safe_tx_hash" text,
  "dao_slug" "config"."dao_slug",
  "kind" text,
  "safe_address" text,
  "chain_id" integer,
  "created_at" timestamp
);

CREATE TABLE IF NOT EXISTS "agora"."citizens" (
  "address" text,
  "dao_slug" "config"."dao_slug",
  "retro_funding_round" text,
  "time_created" bigint
);

CREATE TABLE IF NOT EXISTS "agora"."badgeholders" (
  "address" text,
  "dao_slug" "config"."dao_slug",
  "retro_funding_round" text,
  "time_created" bigint,
  "metadata" text
);

CREATE TABLE IF NOT EXISTS "agora"."api_user" (
  "id" text,
  "api_key" text,
  "email" text,
  "address" text,
  "chain_id" text,
  "description" text,
  "enabled" boolean,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE IF NOT EXISTS "agora"."chain" (
  "id" text,
  "name" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE IF NOT EXISTS "config"."contracts" (
  "address" text,
  "chain" text,
  "contract_type" text,
  "dao" text,
  "env" text
);

CREATE TABLE IF NOT EXISTS "snapshot"."proposals_v2" (
  "id" text,
  "dao_slug" "config"."dao_slug",
  "author" text,
  "body" text,
  "choices" text[],
  "created" numeric,
  "end" numeric,
  "link" text,
  "network" text,
  "scores" numeric[],
  "scores_state" text,
  "scores_total" numeric,
  "scores_updated" numeric,
  "snapshot" text,
  "start" numeric,
  "state" text,
  "title" text,
  "type" text,
  "votes" numeric
);

CREATE TABLE IF NOT EXISTS "snapshot"."votes" (
  "id" text,
  "voter" text,
  "created" integer,
  "choice" text,
  "metadata" jsonb,
  "reason" text,
  "app" text,
  "vp" double precision,
  "vp_by_strategy" jsonb,
  "vp_state" text,
  "proposal_id" text,
  "choice_labels" jsonb,
  "dao_slug" text
);

CREATE TABLE IF NOT EXISTS "snapshot"."proposals" (
  "id" text,
  "title" text
);
