-- Generated by infra/postgres/gen-stub.ts from vendor/agora-next/prisma/schema.prisma.
-- Do not edit by hand: re-run the generator instead.

-- prismaWeb2Client and prismaWeb3Client share one PrismaClient/DATABASE_URL

-- (see vendor/agora-next/src/app/lib/prisma.ts), so agora_web2 mirrors the

-- shared agora/config tables from agora_web3 instead of a distinct split.

\connect agora_web2

CREATE SCHEMA IF NOT EXISTS "agora";
CREATE SCHEMA IF NOT EXISTS "config";

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'dao_slug' AND n.nspname = 'config'
  ) THEN
    CREATE TYPE "config"."dao_slug" AS ENUM ('OP', 'ENS', 'UNI', 'NOUNS', 'LYRA', 'ETHERFI', 'UNISWAP', 'CYBER', 'SCROLL', 'DERIVE', 'PGUILD', 'BOOST', 'XAI', 'B3', 'DEMO', 'LINEA', 'TOWNS', 'SYNDICATE', 'ZEROG', 'DEMO2', 'DEMO4', 'DEMO3', 'SHAPE', 'FLEET');
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "agora"."delegate_statements" (
  "address" text,
  "dao_slug" "config"."dao_slug",
  "signature" text,
  "payload" jsonb,
  "twitter" text,
  "discord" text,
  "email" text,
  "created_at" timestamp,
  "updated_at" timestamp,
  "warpcast" text,
  "endorsed" boolean,
  "scw_address" text,
  "notification_preferences" jsonb,
  "stage" text,
  "message_hash" text,
  "created_at_ts" timestamp,
  "updated_at_ts" timestamp
);

CREATE TABLE IF NOT EXISTS "agora"."address_metadata" (
  "address" text,
  "kind" text,
  "dao_slug" "config"."dao_slug",
  "metadata" jsonb,
  "created_at" timestamp
);

CREATE TABLE IF NOT EXISTS "agora"."safe_tracked_transactions" (
  "safe_tx_hash" text,
  "dao_slug" "config"."dao_slug",
  "kind" text,
  "safe_address" text,
  "chain_id" integer,
  "created_at" timestamp
);

CREATE TABLE IF NOT EXISTS "agora"."citizens" (
  "address" text,
  "dao_slug" "config"."dao_slug",
  "retro_funding_round" text,
  "time_created" bigint
);

CREATE TABLE IF NOT EXISTS "agora"."badgeholders" (
  "address" text,
  "dao_slug" "config"."dao_slug",
  "retro_funding_round" text,
  "time_created" bigint,
  "metadata" text
);

CREATE TABLE IF NOT EXISTS "agora"."api_user" (
  "id" text,
  "api_key" text,
  "email" text,
  "address" text,
  "chain_id" text,
  "description" text,
  "enabled" boolean,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE IF NOT EXISTS "agora"."chain" (
  "id" text,
  "name" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE IF NOT EXISTS "config"."contracts" (
  "address" text,
  "chain" text,
  "contract_type" text,
  "dao" text,
  "env" text
);
