-- Hand-written, unlike 02/03 (generated by infra/postgres/gen-stub.ts from
-- vendor/agora-next's Prisma schema): the generator mirrors b3's views,
-- which carry no indexes, and regenerating must not lose this file.
--
-- "fleet"."votes" is the table infra/scripts/scripted-proposal.sh bridges
-- each real on-chain VoteCast into, because CPLS's DaoNodeSync reads votes
-- from Postgres rather than from DAO Node (see docs/compatibility-notes.md,
-- Task 6, "CPLS reads votes from Postgres, not from DAO Node"). In
-- production a separate indexing pipeline owns that table; here the script
-- does, and without a uniqueness constraint a second bootstrap run against
-- a Postgres volume that survived (`docker compose down` without `-v`,
-- with a fresh Anvil, which redeploys deterministically to the same
-- addresses and so recomputes the same proposal ids) inserted a second copy
-- of all five votes. CPLS counts rows straight out of this table
-- (`num_of_votes`) and writes them all to the archive, so the duplicates
-- reach Agora Next's vote list.
--
-- One vote per (contract, proposal_id, voter) is exactly the chain's own
-- rule: AgoraGovernor's _countVote reverts with GovernorAlreadyCastVote on
-- a second vote from the same account on the same proposal. The insert uses
-- ON CONFLICT DO NOTHING against this index, so a re-run is a no-op rather
-- than an error.
\connect agora_web3

CREATE UNIQUE INDEX IF NOT EXISTS "votes_contract_proposal_voter_key"
  ON "fleet"."votes" ("contract", "proposal_id", "voter");
