import { writeFileSync, readFileSync } from "node:fs";
import { BaseError, ContractFunctionRevertedError, createPublicClient, createWalletClient, decodeErrorResult, decodeEventLog, parseAbi, http, keccak256, toHex, type Hex } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { baseSepolia } from "viem/chains";
import { agoraGovernorAbi, taskLedgerAbi, fleetVotesAbi } from "@fleet/abi";
import { encodeRecordDecision } from "@fleet/sdk";
import { proposalCreditsAbi, proposalTokenAbi } from "./proposal-credits.js";
import { readComputeObject } from "./compute-store.js";
import { writeControlObject } from "./compute-admin.js";
import { readSecret } from "./google.js";

/** Scripted protocol acceptance, explicitly not a model-agent experiment. CI only. */
async function verify() {
  if (!process.env.GITHUB_ACTIONS) throw new Error("CI only.");
  const saved = await readComputeObject("contracts/token-governance-v3-verification.json");
  if (saved) { writeFileSync("token-governance-verification.json", JSON.stringify(saved, null, 2)); return; }
  const manifest = await readComputeObject("contracts/token-governance-v3.json") as {
    addresses: { governor: Hex; ledger: Hex; token: Hex }; proposalBudget: { address: Hex }; deploymentBlock: number;
  } | null;
  if (!manifest) throw new Error("Deploy token governance first.");
  const rpcUrl = await readSecret("fleet-base-sepolia-rpc-url");
  const reader = createPublicClient({ chain: baseSepolia, transport: http(rpcUrl) });
  if (await reader.getChainId() !== 84532) throw new Error("Wrong chain.");
  const bundle = JSON.parse(await readSecret("fleet-base-sepolia-wallets"));
  if (bundle.schema !== "fleet.wallets.v1" || bundle.chainId !== 84532) throw new Error("Wrong wallets.");
  const wallets = Array.from({ length: 5 }, (_, i) => createWalletClient({ account: privateKeyToAccount(bundle.keys[`FLEET_AGENT_KEY_${i}`]), chain: baseSepolia, transport: http(rpcUrl) }));
  const operator = createWalletClient({ account: privateKeyToAccount(bundle.keys.FLEET_OPERATOR_KEY), chain: baseSepolia, transport: http(rpcUrl) });
  const { governor, ledger, token } = manifest.addresses;
  const bank = manifest.proposalBudget.address;
  await writeControlObject("contracts/token-governance-v3-verification-claim.json", { workflowRun: process.env.GITHUB_RUN_ID });
  const transactions: Hex[] = [];
  const confirmed = async (hash: Hex) => {
    transactions.push(hash);
    await writeControlObject(`contracts/token-governance-v3-proof-tx-${transactions.length}.json`, { hash });
    const receipt = await reader.waitForTransactionReceipt({ hash, confirmations: 3 });
    if (receipt.status !== "success") throw new Error("Protocol test transaction reverted.");
    return receipt;
  };
  const charter = JSON.parse(readFileSync("experiments/fixtures/charters/coding-task.v1.json", "utf8"));
  charter.goal = "Scripted protocol acceptance: verify ERC-20 scarcity, atomic fees and unpenalised voting. No model agents or compute allocation.";
  const opened = await confirmed(await operator.writeContract({ address: ledger, abi: taskLedgerAbi, functionName: "openTask", args: [JSON.stringify(charter), 3600n], gas: 700000n, maxFeePerGas: 10000000n }));
  const event = opened.logs.flatMap(log => { try { return [decodeEventLog({ abi: taskLedgerAbi, eventName: "TaskOpened", data: log.data, topics: log.topics })]; } catch { return []; } })[0];
  if (!event) throw new Error("Missing task receipt.");
  const taskId = event.args.taskId;
  const block = await reader.getBlock();
  await confirmed(await operator.writeContract({ address: bank, abi: proposalCreditsAbi, functionName: "registerRunPolicy",
    args: [taskId, keccak256(toHex("fleet-token-governance-v3-protocol-test")), 1, block.timestamp + 3300n, 1, 10n ** 18n, wallets.map(w => w.account.address)], gas: 2500000n, maxFeePerGas: 10000000n }));
  const budgetToken = await reader.readContract({ address: bank, abi: proposalCreditsAbi, functionName: "proposalToken", args: [taskId] });
  const argsFor = (label: string) => {
    const data = encodeRecordDecision({ taskId, kind: "CHOOSE_PATH", expectedVersion: 1, payloadHash: keccak256(toHex(label)), newCharterText: "", summary: label });
    return [[ledger], [0n], [data], `# ${label}\n\nSCRIPTED PROTOCOL ACCEPTANCE TEST. These transactions are sent by CI to verify contract enforcement, not generated by model agents. Voting against carries no token penalty.\n\n#proposalTypeId=0`] as const;
  };
  const first = argsFor("Verify cancellation does not refund FPROP");
  const firstId = await reader.readContract({ address: governor, abi: agoraGovernorAbi, functionName: "getProposalId", args: [first[0], first[1], first[2], keccak256(toHex(first[3]))] });
  await confirmed(await wallets[0]!.writeContract({ address: governor, abi: agoraGovernorAbi, functionName: "propose", args: first, gas: 1200000n, maxFeePerGas: 10000000n }));
  await confirmed(await wallets[0]!.writeContract({ address: governor, abi: agoraGovernorAbi, functionName: "cancel", args: [first[0], first[1], first[2], keccak256(toHex(first[3]))], gas: 300000n, maxFeePerGas: 10000000n }));
  if (await reader.readContract({ address: budgetToken, abi: proposalTokenAbi, functionName: "balanceOf", args: [wallets[0]!.account.address] }) !== 0n) throw new Error("Cancellation refunded tokens.");
  // Verify the exact hook revert, not an arbitrary RPC error.
  const spam = argsFor("Rejected: empty proposal token balance");
  let refused = false;
  try { await reader.simulateContract({ account: wallets[0]!.account, address: governor, abi: agoraGovernorAbi, functionName: "propose", args: spam }); }
  catch (error) {
    if (error instanceof BaseError) {
      const cause = error.walk(e => e instanceof ContractFunctionRevertedError);
      if (cause instanceof ContractFunctionRevertedError) {
        refused = cause.data?.errorName === "HookCallFailed";
        if (!refused && cause.raw) {
          try { refused = decodeErrorResult({ abi: parseAbi(["error HookCallFailed()"]), data: cause.raw }).errorName === "HookCallFailed"; } catch {}
        }
      }
    }
  }
  if (!refused) throw new Error("Empty-budget direct proposal was not verifiably rejected by the hook.");
  const second = argsFor("Reject this test request while retaining the right to vote");
  const proposalId = await reader.readContract({ address: governor, abi: agoraGovernorAbi, functionName: "getProposalId", args: [second[0], second[1], second[2], keccak256(toHex(second[3]))] });
  const proposalReceipt = await confirmed(await wallets[1]!.writeContract({ address: governor, abi: agoraGovernorAbi, functionName: "propose", args: second, gas: 1200000n, maxFeePerGas: 10000000n }));
  const snapshot = await reader.readContract({ address: governor, abi: agoraGovernorAbi, functionName: "proposalSnapshot", args: [proposalId] });
  while ((await reader.getBlock()).timestamp <= snapshot) await new Promise(resolve => setTimeout(resolve, 2000));
  for (const [i, wallet] of wallets.entries()) await confirmed(await wallet.writeContract({ address: governor, abi: agoraGovernorAbi, functionName: "castVoteWithReason",
    args: [proposalId, 0, `Agent${i + 1}: scripted protocol test. Reject this request to verify that a defeated proposal retains its ERC-20 fee. Objections and voting consume no FPROP.`], gas: 350000n, maxFeePerGas: 10000000n }));
  const deadline = await reader.readContract({ address: governor, abi: agoraGovernorAbi, functionName: "proposalDeadline", args: [proposalId] });
  while ((await reader.getBlock()).timestamp <= deadline) await new Promise(resolve => setTimeout(resolve, 3000));
  const state = await reader.readContract({ address: governor, abi: agoraGovernorAbi, functionName: "state", args: [proposalId] });
  const supply = await reader.readContract({ address: budgetToken, abi: proposalTokenAbi, functionName: "totalSupply" });
  const agent0Voted = await reader.readContract({ address: governor, abi: agoraGovernorAbi, functionName: "hasVoted", args: [proposalId, wallets[0]!.account.address] });
  const votesSupply = await reader.readContract({ address: token, abi: fleetVotesAbi, functionName: "totalSupply" });
  if (state !== 3 || supply !== 3n || !agent0Voted || votesSupply !== 5n * 10n ** 18n) throw new Error("Protocol acceptance did not pass.");
  const proof = { chainId: 84532, scripted: true, modelAgents: false, governor, proposalToken: budgetToken,
    taskId: taskId.toString(), cancelledProposalId: firstId.toString(), proposalId: proposalId.toString(), expectedBallots: 5,
    transactionHash: proposalReceipt.transactionHash, initialSupply: 5, remainingSupply: Number(supply),
    exhaustedAgentCouldVote: agent0Voted, directUnpaidProposalRejected: refused, cancelledAndDefeatedFeesRetained: true,
    outcome: "Defeated", transactions, workflowRun: process.env.GITHUB_RUN_ID };
  await writeControlObject("contracts/token-governance-v3-verification.json", proof);
  writeFileSync("token-governance-verification.json", JSON.stringify(proof, null, 2));
  console.log(JSON.stringify(proof));
}
verify().catch(() => { console.error("Protocol verification incomplete. Protected transaction receipts remain available; no automatic replay."); process.exitCode = 1; });
