name: fleet-base-sepolia-events
resource_size: xs
sources:
  fleet_logs:
    type: dataset
    dataset_name: base_sepolia.raw_logs
    version: 1.0.0
    primary_key: id
    start_at: earliest
    filter: >-
      block_number >= 46907131 AND
      address IN ('0x7d49b367a4c028c886a90ab8648e94e37b57a3d3', '0xde04508b1b46a35c9fd947ccafabdf78ffebf79a')
transforms:
  fleet_events:
    type: sql
    primary_key: id
    sql: |
      SELECT id, address, block_number, block_hash, transaction_hash,
             transaction_index, log_index, data, topics, block_timestamp, _gs_op
      FROM fleet_logs
      WHERE block_number >= 46907131 AND address IN
        ('0x7d49b367a4c028c886a90ab8648e94e37b57a3d3', '0xde04508b1b46a35c9fd947ccafabdf78ffebf79a')
sinks:
  history:
    type: webhook
    from: fleet_events
    url: https://fleet-governance-indexer-449245570324.us-central1.run.app/goldsky
    secret_name: FLEET_GOVERNANCE_HISTORY
    primary_key: id
    one_row_per_request: false
    batch_size: 100
    batch_flush_interval: 1s
